name: CI

on:
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build
        run: swift build

      - name: Test
        run: swift test
